title: Ruud van Dommelen 
#email: -
description: >- # this means to ignore newlines until "baseurl:"
  Software | Robotics | Mechatronics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruudvandommelen.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RuudVanDommelen
github_username:  ruudvd

# Build settings
theme: jekyll-theme-cayman
# plugins:

show_downloads: false
google_analytics: G-SERYNGYD3W

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
